services:
  mysql:
    image: mysql:8.0.39
    container_name: pg-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mxshop
    ports:
      - "23306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: pg-redis
    restart: always
    ports:
      - "26379:6379"  # 修改为 Redis 默认端口

volumes:
  mysql_data:
